name: Aggiorna Casella Giornaliera Temporaneo

on:
  schedule:
    - cron: '15 20 30 11 *'  # 30 novembre alle 20:15 UTC
  workflow_dispatch:        # permette anche l'avvio manuale

jobs:
  call_endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Controlla orario esecuzione
        run: date
      - name: Chiamata HTTP all'endpoint
        run: |
          curl -X GET https://calendariopubblicobackend.onrender.com/cron/aggiorna
